# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nnode.proto\x12\x04node"O\n\x07Message\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0b\n\x03ttl\x18\x02 \x01(\x05\x12\x0c\n\x04hash\x18\x03 \x01(\x03\x12\x0b\n\x03\x63md\x18\x04 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t"\x07\n\x05\x45mpty" \n\x10HandShakeRequest\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t2\x9f\x01\n\x0cNodeServices\x12\x30\n\thandshake\x12\x16.node.HandShakeRequest\x1a\x0b.node.Empty\x12\x31\n\ndisconnect\x12\x16.node.HandShakeRequest\x1a\x0b.node.Empty\x12*\n\x0csend_message\x12\r.node.Message\x1a\x0b.node.Emptyb\x06proto3'
)


_MESSAGE = DESCRIPTOR.message_types_by_name["Message"]
_STATUS = DESCRIPTOR.message_types_by_name["Status"]
_EMPTY = DESCRIPTOR.message_types_by_name["Empty"]
_HANDSHAKEREQUEST = DESCRIPTOR.message_types_by_name["HandShakeRequest"]
Message = _reflection.GeneratedProtocolMessageType(
    "Message",
    (_message.Message,),
    {
        "DESCRIPTOR": _MESSAGE,
        "__module__": "node_pb2"
        # @@protoc_insertion_point(class_scope:node.Message)
    },
)
_sym_db.RegisterMessage(Message)

Status = _reflection.GeneratedProtocolMessageType(
    "Status",
    (_message.Message,),
    {
        "DESCRIPTOR": _STATUS,
        "__module__": "node_pb2"
        # @@protoc_insertion_point(class_scope:node.Status)
    },
)
_sym_db.RegisterMessage(Status)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "node_pb2"
        # @@protoc_insertion_point(class_scope:node.Empty)
    },
)
_sym_db.RegisterMessage(Empty)

HandShakeRequest = _reflection.GeneratedProtocolMessageType(
    "HandShakeRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _HANDSHAKEREQUEST,
        "__module__": "node_pb2"
        # @@protoc_insertion_point(class_scope:node.HandShakeRequest)
    },
)
_sym_db.RegisterMessage(HandShakeRequest)

_NODESERVICES = DESCRIPTOR.services_by_name["NodeServices"]
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _MESSAGE._serialized_start = 20
    _MESSAGE._serialized_end = 99
    _STATUS._serialized_start = 101
    _STATUS._serialized_end = 125
    _EMPTY._serialized_start = 127
    _EMPTY._serialized_end = 134
    _HANDSHAKEREQUEST._serialized_start = 136
    _HANDSHAKEREQUEST._serialized_end = 168
    _NODESERVICES._serialized_start = 171
    _NODESERVICES._serialized_end = 330
# @@protoc_insertion_point(module_scope)
