# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edge_node.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x64ge_node.proto\x12\tedge_node\x1a\x1bgoogle/protobuf/empty.proto\"Y\n\x0b\x45\x64geMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x03(\t\x12\x14\n\x07weights\x18\x04 \x01(\x0cH\x00\x88\x01\x01\x42\n\n\x08_weights2J\n\x04Node\x12\x42\n\nMainStream\x12\x16.edge_node.EdgeMessage\x1a\x16.edge_node.EdgeMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_node_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EDGEMESSAGE']._serialized_start=59
  _globals['_EDGEMESSAGE']._serialized_end=148
  _globals['_NODE']._serialized_start=150
  _globals['_NODE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
