"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
from p2pfl.communication.protocols.edge.proto import edge_node_pb2
import grpc
import grpc.aio # type: ignore
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class NodeStub:
    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    MainStream: grpc.StreamStreamMultiCallable[
        edge_node_pb2.EdgeMessage,
        edge_node_pb2.EdgeMessage,
    ]

class NodeAsyncStub:
    MainStream: grpc.aio.StreamStreamMultiCallable[
        edge_node_pb2.EdgeMessage,
        edge_node_pb2.EdgeMessage,
    ]

class NodeServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def MainStream(
        self,
        request_iterator: _MaybeAsyncIterator[edge_node_pb2.EdgeMessage],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[edge_node_pb2.EdgeMessage], collections.abc.AsyncIterator[edge_node_pb2.EdgeMessage]]: ...

def add_NodeServicer_to_server(servicer: NodeServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
