"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EdgeMessage(google.protobuf.message.Message):
    """python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. node.proto"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CMD_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    WEIGHTS_FIELD_NUMBER: builtins.int
    id: builtins.int
    cmd: builtins.str
    weights: builtins.bytes
    @property
    def message(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        cmd: builtins.str = ...,
        message: collections.abc.Iterable[builtins.str] | None = ...,
        weights: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_weights", b"_weights", "weights", b"weights"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_weights", b"_weights", "cmd", b"cmd", "id", b"id", "message", b"message", "weights", b"weights"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_weights", b"_weights"]) -> typing.Literal["weights"] | None: ...

global___EdgeMessage = EdgeMessage
